<?//Саня сказал что хуйня =). Я с ни согласен. Пиши <?php
/**
 * @var \Customer\AddressBook\Block\AddedBook $block
 */
/** @var \Customer\AddressBook\Model\AddressBook $dataAddressBook */
$dataAddressBook = $block->getDataAddressBookFromCustomer();
?>
<form action="<?= $block->escapeUrl($block->getFormAction()) ?>" method="post">
    <label for=""><?= __('First name') ?></label>
    <?= $block->getBlockHtml('formkey') ?>
    <input name="first_name" type="text" value="<?= $dataAddressBook->getFirstName() ?>">
    <label for=""><?= __('Last name') ?></label>
    <input name="last_name" type="text" value="<?= $dataAddressBook['last_name'] ?>">
    <label for=""><?= __('Phone') ?></label>
    <input name="phone_number" type="text" value="<?= $dataAddressBook['phone_number'] ?>">
<!-- customer_id filed is redudant, because we have customer ID in the session.     -->
    <input type="hidden" value="<?= $block->getIdCustomer() ?>" name="customer_id">
    <? if ($dataAddressBook['address_book_id']) { ?>
        <input type="hidden" value="<?= $dataAddressBook['address_book_id'] ?>" name="address_book_id">
    <? } ?>
    <input type="submit" value="<?= __('Save address book') ?>">
</form>
